# Copyright (c) 2026 David Michael Indraputra

"""Python BaseAgent runtime and deterministic agent harness."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .agent.base_agent import AgentWatchdogPolicy, BaseAgent, ToolHookDecision
    from .agent.elastic_context import render_elastic_instructions
    from .agent.graph_agent_executor import (
        ElasticBindingFactory,
        GraphAgentBinding,
        GraphAgentExecutor,
    )
    from .agent.model import (
        AgentModel,
        FailoverAgentModel,
        ModelFailoverAttempt,
        ModelStreamCompleted,
        ModelStreamEvent,
        ModelStreamListener,
        ModelTextDelta,
        ModelToolCallDelta,
        ModelTurnResponse,
        ProviderContinuation,
        ProviderToolResult,
        ProviderToolResultConsumer,
        ProviderUsage,
        ScriptedModel,
        StreamingAgentModel,
    )
    from .agent.openai_compatible import (
        HttpxJsonTransport,
        HttpxStreamingJsonTransport,
        ImageBytesLoader,
        JsonHttpTransport,
        OpenAICompatibleAgentModel,
        OpenAICompatibleEmbeddingProvider,
        OpenAICompatibleEndpoint,
        OpenAICompatibleVisionAdapter,
        SourceVerifiedImageLoader,
        StreamingJsonHttpTransport,
        UrlLibJsonTransport,
    )
    from .agent.orchestrator import (
        AgentExecutionProfile,
        GraphAgentBindingContext,
        GraphAgentBindingFactory,
        OrchestrationPolicy,
        OrchestrationRecord,
        OrchestrationRequest,
        OrchestrationStateStore,
        OrchestrationStatus,
        Orchestrator,
        UserModelSelection,
        WorkerAssignment,
    )
    from .agent.retention import (
        RetentionPolicy,
        RetentionReport,
        RunRetention,
        RunTombstone,
        prune_run_root,
        read_tombstones,
    )
    from .agent.runtime import AgentRuntimeServices
    from .agent.task_runner import (
        AgentTaskRunner,
        ModelEndpointOptions,
        PermissionOptions,
        TaskOptionError,
        TaskRunOptions,
    )
    from .agent.verification import (
        CallableVerificationGate,
        VerificationContext,
        VerificationDecision,
        VerificationGate,
        VerificationGateRegistry,
    )
    from .foundations.benchmarks import (
        PckpBenchmarkCase,
        PckpBenchmarkReport,
        PckpBenchmarkResult,
        load_pckp_cases,
        run_pckp_benchmark,
        write_pckp_benchmark_report,
    )
    from .foundations.contracts import (
        AgentDefinition,
        AgentFailure,
        AgentResult,
        AgentRunStatus,
        CompactedEpisodeStub,
        ContextProjectionMetadata,
        ModelBinding,
        RuntimeOptions,
        ScopedAgentTask,
        SkillContext,
        TaskScope,
        TerminationPolicy,
        ToolBatchTurn,
        ToolCall,
        ToolConcurrency,
        ToolResultHandle,
        VersionedInstructions,
    )
    from .foundations.optimization import (
        ExactPckpSolver,
        GreedyPckpBaseline,
        PckpItem,
        PckpProblem,
        PckpSolution,
        PckpStatus,
    )
    from .integrations import (
        ExplorationCandidate,
        InMemoryInteropReceiptStore,
        InMemoryJevReceiptStore,
        InteropFailureMode,
        InteropOperationStatus,
        InteropReceipt,
        InteropReceiptSink,
        InteropRunEnvelope,
        JevAdvisoryPolicy,
        JevAdvisoryVerificationGate,
        JevArchitectureAdvice,
        JevArchitectureRouter,
        JevArchitectureRoutingPolicy,
        JevChoiceQuestion,
        JevDecisionRequest,
        JevExplorationAdvisor,
        JevNoulQuestion,
        JevQuestionSpec,
        JevScoreQuestion,
        LangChainAgentModelAdapter,
        LangChainSdkRunnable,
        LangChainSdkToolFacade,
        LangGraphApprovalChallenge,
        LangGraphNodeExecutor,
        LangGraphSdkNode,
        LangGraphSdkNodeBinding,
        TelemetryInteropReceiptSink,
        TelemetryJevReceiptSink,
        TypeSafeJevDecisionEvaluator,
        build_langgraph_state_graph,
        langgraph_interrupt_payload,
        parse_structured_sdk_turn,
    )
    from .mcp.client import McpClientManager, McpServerNotConnectedError
    from .mcp.client_bridge import mcp_tools_as_extensions, registered_tool_name
    from .mcp.client_types import (
        McpConnectionState,
        McpConnectionStatus,
        McpHttpServerConfig,
        McpResourceInfo,
        McpServerConfig,
        McpStdioServerConfig,
        McpToolInfo,
        McpTransportKind,
    )
    from .mcp.server import create_mcp_server
    from .memory.context import assemble_initial_context
    from .memory.context_projection import (
        ContextProjection,
        ContextProjectionPolicy,
        ContextProjector,
        FileToolResultJournal,
        InMemoryToolResultJournal,
        ToolResultJournal,
    )
    from .memory.episode_models import (
        CompactionResult,
        CompactionStatus,
        CompactionStrategy,
        EpisodeCheckpoint,
        EpisodeRecord,
        EpisodeRelevanceScorer,
        EpisodeState,
        PaskCompactionPolicy,
    )
    from .memory.episode_scoring import LexicalEpisodeRelevanceScorer
    from .memory.episode_store import FileEpisodeStore, InMemoryEpisodeStore
    from .memory.episodes import InMemoryEpisodeGraph
    from .observability.audit_log import AuditLogEntry, AuditTranscriptStore
    from .observability.metric_definitions import STANDARD_METRIC_DEFINITIONS
    from .observability.metrics import (
        record_metric_unavailable,
        record_metric_value,
        register_standard_metric_definitions,
    )
    from .observability.profiler import (
        AgentRunProfile,
        AgentRunProfiler,
        ProfilePhaseSummary,
        ProfileSpan,
        ProfileSpanHandle,
        ProfileSpanKind,
        ProfileSpanStatus,
    )
    from .observability.telemetry_helpers import metric_observation
    from .observability.telemetry_models import (
        ChainBreak,
        MetricAvailability,
        MetricDefinition,
        MetricObservation,
        TelemetryActor,
        TelemetryAuthority,
        TelemetryContext,
        TelemetryEvent,
        TelemetryRunSummary,
        TelemetrySeverity,
    )
    from .observability.telemetry_store import TelemetryStore
    from .specifications.documents import (
        DocumentFormat,
        DocumentNode,
        DocumentNodeKind,
        DocumentTree,
        SourceRef,
        SpecificationCategory,
        SpecificationManifest,
        VisionStatus,
    )
    from .specifications.evidence_graph import (
        ClosureWitness,
        EvidenceGraph,
        EvidenceNode,
        EvidenceNodeKind,
        EvidenceOmission,
        EvidenceRelation,
        EvidenceRelationKind,
        EvidenceSelectionPolicy,
        EvidenceSelectionRequest,
        EvidenceSelectionResult,
        EvidenceSelectionStatus,
        StructuralContextSelector,
    )
    from .specifications.preprocessing import SpecificationPreprocessor
    from .specifications.retrieval import (
        DeterministicLexicalRetrievalIndex,
        EmbeddingProvider,
        GroundedRetrievalService,
        InMemoryRetrievalCache,
        QdrantRetrievalIndex,
        RedisRetrievalCache,
        RetrievalCache,
        RetrievalIndex,
        RetrievalTelemetrySink,
        specification_retrieval_documents,
    )
    from .specifications.retrieval_models import (
        ResolvedRetrieval,
        RetrievalCandidate,
        RetrievalDocument,
        RetrievalFailureMode,
        RetrievalQuery,
        RetrievalResult,
        RetrievalStatus,
    )
    from .specifications.vision import (
        ScriptedVisionAdapter,
        UnconfiguredVisionAdapter,
        VisionAdapter,
        VisionProposal,
    )
    from .state.controller_runtime import ControllerRuntime
    from .state.coordination_records import RunRecord
    from .state.elastic import (
        DEFAULT_MAX_ELASTIC_DEPTH,
        DEFAULT_MAX_ELASTIC_NODES,
        ELASTIC_REQUEST_TOOL_NAME,
        MAX_ELASTIC_DEPTH_LIMIT,
        MAX_ELASTIC_NODES_LIMIT,
        MAX_ELASTIC_REQUESTS_PER_RESULT,
        ElasticCapacity,
        ElasticNodeRole,
        ElasticNodeSpec,
        ElasticRefusalCode,
        ElasticReservation,
        ElasticSpawnRequest,
        GraphCapacityGrant,
        GraphSpawnRecord,
        GraphSpawnStatus,
    )
    from .state.graph import StateGraph
    from .state.graph_models import (
        GraphEdge,
        GraphEdgeKind,
        GraphNode,
        GraphNodeExecutionContext,
        GraphNodeKind,
        GraphNodeResult,
        GraphNodeStatus,
        GraphSharedState,
        GraphStateConflict,
        GraphStateConflictKind,
        ReplayPolicy,
    )
    from .state.harness_coordinator import HarnessCoordinator
    from .state.orchestration import ControllerStateMachine
    from .state.orchestration_models import (
        ComplexityRouter,
        ComplexityRoutingRules,
        ControllerPhase,
        ControllerRecord,
        GapMetadata,
        ReconcileAction,
        ReconcileReport,
        SkillToolProfile,
        WorkflowArchitecture,
    )
    from .state.planning import (
        DependencyProof,
        ModelTier,
        Plan,
        PlanTask,
        PlanValidationReport,
        PlanValidator,
        TaskSignalUse,
    )
    from .state.project_state_engine import ProjectStateProjector, ProjectStateReducer
    from .state.project_state_models import (
        ArtifactStatus,
        DecisionStatus,
        OpenQuestion,
        ProjectArtifactState,
        ProjectBlocker,
        ProjectDecision,
        ProjectState,
        ProjectStateEvent,
        ProjectStateProjectionPolicy,
        ProjectStateView,
        ProjectWorkItem,
        QuestionOwner,
        StageStateField,
        StageStateSchema,
        StateAction,
        StateAuthority,
        StateEvidence,
        StateTransition,
        StateTransitionKind,
        WorkItemStatus,
        make_project_state,
    )
    from .state.project_state_store import FileProjectStateStore, InMemoryProjectStateStore
    from .state.run_state_store import RunStateStore
    from .state.shared_state import (
        DiscoveryRouteDecision,
        DiscoveryRouteStatus,
        DiscoveryRoutingIndex,
        DiscoveryRoutingRefs,
        ExploratoryDiscovery,
        LateralDependencyRequest,
        ProvenanceContractGate,
        ProvenanceGateDecision,
        ProvenanceRecord,
        SharedSubstrateSnapshot,
        make_provenance_record,
    )
    from .tools.approvals import ApprovalRegistry, ApprovalRequest, ApprovalStatus
    from .tools.artifacts import ArtifactRecord, ArtifactStore, ArtifactWriteOccurrence
    from .tools.core import (
        CoreToolDispatcher,
        CoreToolServices,
        DuckDuckGoHtmlClient,
        SearchResult,
        core_tool_definitions,
    )
    from .tools.delegation import DelegatedRunContext, DelegatedRunFactory, SubagentCoordinator
    from .tools.elastic_requests import (
        ElasticRequestBuffer,
        ElasticRequestRejected,
        ElasticRequestToolExecutor,
    )
    from .tools.policy import CapabilityGrant, CapabilityPolicy, SideEffectClass
    from .tools.registry import (
        HarnessExecutionContext,
        HarnessToolExecutor,
        HarnessToolHandler,
        HarnessToolRegistry,
        RegisteredTool,
    )
    from .tools.sandbox import DockerSandbox, DockerUnavailableError, NativeSandbox, SandboxBackend
    from .tools.sandbox_models import DockerSandboxOptions, EnvironmentPolicy, SandboxKind
    from .tools.supervisor import (
        CommandTemplate,
        ProcessExecutionRecord,
        ProcessExitKind,
        ProcessSupervisor,
        ResourceLimits,
        RetryPolicy,
        WatchdogController,
        WatchdogState,
    )
    from .tools.task_models import TaskKind, TaskRecord, TaskStatus
    from .tools.tasks import BackgroundTaskManager
    from .tools.worktree_models import AgentWorktreeInfo
    from .tools.worktrees import AgentWorktreeManager, validate_worktree_slug

_EXPORTS: dict[str, str] = {
    "AgentDefinition": ".foundations.contracts",
    "AgentFailure": ".foundations.contracts",
    "AgentExecutionProfile": ".agent.orchestrator",
    "AgentModel": ".agent.model",
    "AgentResult": ".foundations.contracts",
    "AgentRunProfile": ".observability.profiler",
    "AgentRunProfiler": ".observability.profiler",
    "AgentRunStatus": ".foundations.contracts",
    "AgentRuntimeServices": ".agent.runtime",
    "AgentTaskRunner": ".agent.task_runner",
    "ModelEndpointOptions": ".agent.task_runner",
    "PermissionOptions": ".agent.task_runner",
    "TaskOptionError": ".agent.task_runner",
    "TaskRunOptions": ".agent.task_runner",
    "RetentionPolicy": ".agent.retention",
    "RetentionReport": ".agent.retention",
    "RunRetention": ".agent.retention",
    "RunTombstone": ".agent.retention",
    "prune_run_root": ".agent.retention",
    "read_tombstones": ".agent.retention",
    "AgentWatchdogPolicy": ".agent.base_agent",
    "AgentWorktreeInfo": ".tools.worktree_models",
    "AgentWorktreeManager": ".tools.worktrees",
    "AuditLogEntry": ".observability.audit_log",
    "AuditTranscriptStore": ".observability.audit_log",
    "PckpBenchmarkCase": ".foundations.benchmarks",
    "PckpBenchmarkReport": ".foundations.benchmarks",
    "PckpBenchmarkResult": ".foundations.benchmarks",
    "ApprovalRegistry": ".tools.approvals",
    "ApprovalRequest": ".tools.approvals",
    "ApprovalStatus": ".tools.approvals",
    "ArtifactRecord": ".tools.artifacts",
    "ArtifactStore": ".tools.artifacts",
    "ArtifactWriteOccurrence": ".tools.artifacts",
    "BackgroundTaskManager": ".tools.tasks",
    "BaseAgent": ".agent.base_agent",
    "CapabilityGrant": ".tools.policy",
    "CapabilityPolicy": ".tools.policy",
    "CommandTemplate": ".tools.supervisor",
    "CompactedEpisodeStub": ".foundations.contracts",
    "ComplexityRouter": ".state.orchestration_models",
    "ComplexityRoutingRules": ".state.orchestration_models",
    "ContextProjection": ".memory.context_projection",
    "ContextProjectionMetadata": ".foundations.contracts",
    "ContextProjectionPolicy": ".memory.context_projection",
    "ContextProjector": ".memory.context_projection",
    "CoreToolDispatcher": ".tools.core",
    "CoreToolServices": ".tools.core",
    "CompactionResult": ".memory.episode_models",
    "CompactionStrategy": ".memory.episode_models",
    "CompactionStatus": ".memory.episode_models",
    "ControllerPhase": ".state.orchestration_models",
    "ControllerRecord": ".state.orchestration_models",
    "ControllerRuntime": ".state.controller_runtime",
    "ControllerStateMachine": ".state.orchestration",
    "DelegatedRunContext": ".tools.delegation",
    "DelegatedRunFactory": ".tools.delegation",
    "DeterministicLexicalRetrievalIndex": ".specifications.retrieval",
    "DependencyProof": ".state.planning",
    "DockerSandbox": ".tools.sandbox",
    "DockerSandboxOptions": ".tools.sandbox_models",
    "DockerUnavailableError": ".tools.sandbox",
    "EmbeddingProvider": ".specifications.retrieval",
    "EnvironmentPolicy": ".tools.sandbox_models",
    "DocumentFormat": ".specifications.documents",
    "DocumentNode": ".specifications.documents",
    "DocumentNodeKind": ".specifications.documents",
    "DuckDuckGoHtmlClient": ".tools.core",
    "DocumentTree": ".specifications.documents",
    "EpisodeCheckpoint": ".memory.episode_models",
    "EpisodeRelevanceScorer": ".memory.episode_models",
    "EpisodeRecord": ".memory.episode_models",
    "EpisodeState": ".memory.episode_models",
    "ExploratoryDiscovery": ".state.shared_state",
    "FailoverAgentModel": ".agent.model",
    "FileEpisodeStore": ".memory.episode_store",
    "FileToolResultJournal": ".memory.context_projection",
    "GapMetadata": ".state.orchestration_models",
    "GraphEdge": ".state.graph_models",
    "GraphEdgeKind": ".state.graph_models",
    "GraphNode": ".state.graph_models",
    "GraphNodeExecutionContext": ".state.graph_models",
    "GraphNodeKind": ".state.graph_models",
    "GraphNodeResult": ".state.graph_models",
    "GraphNodeStatus": ".state.graph_models",
    "ReplayPolicy": ".state.graph_models",
    "GraphSharedState": ".state.graph_models",
    "GraphStateConflict": ".state.graph_models",
    "GraphStateConflictKind": ".state.graph_models",
    "GroundedRetrievalService": ".specifications.retrieval",
    "HarnessCoordinator": ".state.harness_coordinator",
    "HarnessExecutionContext": ".tools.registry",
    "HarnessToolExecutor": ".tools.registry",
    "HarnessToolHandler": ".tools.registry",
    "HarnessToolRegistry": ".tools.registry",
    "HttpxJsonTransport": ".agent.openai_compatible",
    "HttpxStreamingJsonTransport": ".agent.openai_compatible",
    "InMemoryEpisodeGraph": ".memory.episodes",
    "InMemoryEpisodeStore": ".memory.episode_store",
    "InMemoryRetrievalCache": ".specifications.retrieval",
    "InMemoryToolResultJournal": ".memory.context_projection",
    "ImageBytesLoader": ".agent.openai_compatible",
    "JsonHttpTransport": ".agent.openai_compatible",
    "LateralDependencyRequest": ".state.shared_state",
    "LexicalEpisodeRelevanceScorer": ".memory.episode_scoring",
    "McpClientManager": ".mcp.client",
    "McpConnectionState": ".mcp.client_types",
    "McpConnectionStatus": ".mcp.client_types",
    "McpHttpServerConfig": ".mcp.client_types",
    "McpResourceInfo": ".mcp.client_types",
    "McpServerConfig": ".mcp.client_types",
    "McpServerNotConnectedError": ".mcp.client",
    "McpStdioServerConfig": ".mcp.client_types",
    "McpToolInfo": ".mcp.client_types",
    "McpTransportKind": ".mcp.client_types",
    "MetricAvailability": ".observability.telemetry_models",
    "MetricDefinition": ".observability.telemetry_models",
    "MetricObservation": ".observability.telemetry_models",
    "ModelBinding": ".foundations.contracts",
    "ModelFailoverAttempt": ".agent.model",
    "ModelStreamCompleted": ".agent.model",
    "ModelStreamEvent": ".agent.model",
    "ModelStreamListener": ".agent.model",
    "ModelTextDelta": ".agent.model",
    "ModelTier": ".state.planning",
    "ModelToolCallDelta": ".agent.model",
    "ModelTurnResponse": ".agent.model",
    "NativeSandbox": ".tools.sandbox",
    "OpenAICompatibleAgentModel": ".agent.openai_compatible",
    "OpenAICompatibleEmbeddingProvider": ".agent.openai_compatible",
    "OpenAICompatibleEndpoint": ".agent.openai_compatible",
    "OpenAICompatibleVisionAdapter": ".agent.openai_compatible",
    "OrchestrationPolicy": ".agent.orchestrator",
    "OrchestrationRecord": ".agent.orchestrator",
    "OrchestrationRequest": ".agent.orchestrator",
    "OrchestrationStateStore": ".agent.orchestrator",
    "OrchestrationStatus": ".agent.orchestrator",
    "Orchestrator": ".agent.orchestrator",
    "Plan": ".state.planning",
    "PlanTask": ".state.planning",
    "PlanValidationReport": ".state.planning",
    "PlanValidator": ".state.planning",
    "ProfilePhaseSummary": ".observability.profiler",
    "ProfileSpan": ".observability.profiler",
    "ProfileSpanHandle": ".observability.profiler",
    "ProfileSpanKind": ".observability.profiler",
    "ProfileSpanStatus": ".observability.profiler",
    "ProcessExecutionRecord": ".tools.supervisor",
    "ProcessExitKind": ".tools.supervisor",
    "ProcessSupervisor": ".tools.supervisor",
    "PaskCompactionPolicy": ".memory.episode_models",
    "ProviderContinuation": ".agent.model",
    "ProviderToolResult": ".agent.model",
    "ProviderToolResultConsumer": ".agent.model",
    "ProviderUsage": ".agent.model",
    "ProvenanceContractGate": ".state.shared_state",
    "ProvenanceGateDecision": ".state.shared_state",
    "ProvenanceRecord": ".state.shared_state",
    "QdrantRetrievalIndex": ".specifications.retrieval",
    "ReconcileAction": ".state.orchestration_models",
    "ReconcileReport": ".state.orchestration_models",
    "RedisRetrievalCache": ".specifications.retrieval",
    "ResolvedRetrieval": ".specifications.retrieval_models",
    "RetrievalCandidate": ".specifications.retrieval_models",
    "RetrievalCache": ".specifications.retrieval",
    "RetrievalDocument": ".specifications.retrieval_models",
    "RetrievalFailureMode": ".specifications.retrieval_models",
    "RetrievalIndex": ".specifications.retrieval",
    "RetrievalQuery": ".specifications.retrieval_models",
    "RetrievalResult": ".specifications.retrieval_models",
    "RetrievalStatus": ".specifications.retrieval_models",
    "RetrievalTelemetrySink": ".specifications.retrieval",
    "RunRecord": ".state.coordination_records",
    "RunStateStore": ".state.run_state_store",
    "RuntimeOptions": ".foundations.contracts",
    "ResourceLimits": ".tools.supervisor",
    "RegisteredTool": ".tools.registry",
    "RetryPolicy": ".tools.supervisor",
    "ScopedAgentTask": ".foundations.contracts",
    "SearchResult": ".tools.core",
    "STANDARD_METRIC_DEFINITIONS": ".observability.metric_definitions",
    "SharedSubstrateSnapshot": ".state.shared_state",
    "SandboxBackend": ".tools.sandbox",
    "SandboxKind": ".tools.sandbox_models",
    "SideEffectClass": ".tools.policy",
    "SkillContext": ".foundations.contracts",
    "SkillToolProfile": ".state.orchestration_models",
    "SpecificationCategory": ".specifications.documents",
    "SpecificationManifest": ".specifications.documents",
    "SpecificationPreprocessor": ".specifications.preprocessing",
    "ScriptedModel": ".agent.model",
    "ScriptedVisionAdapter": ".specifications.vision",
    "StateGraph": ".state.graph",
    "StreamingAgentModel": ".agent.model",
    "StreamingJsonHttpTransport": ".agent.openai_compatible",
    "SourceRef": ".specifications.documents",
    "SourceVerifiedImageLoader": ".agent.openai_compatible",
    "SubagentCoordinator": ".tools.delegation",
    "TaskKind": ".tools.task_models",
    "TaskRecord": ".tools.task_models",
    "TaskScope": ".foundations.contracts",
    "TaskStatus": ".tools.task_models",
    "TaskSignalUse": ".state.planning",
    "TerminationPolicy": ".foundations.contracts",
    "ChainBreak": ".observability.telemetry_models",
    "TelemetryActor": ".observability.telemetry_models",
    "TelemetryAuthority": ".observability.telemetry_models",
    "TelemetryContext": ".observability.telemetry_models",
    "TelemetryEvent": ".observability.telemetry_models",
    "TelemetryRunSummary": ".observability.telemetry_models",
    "TelemetrySeverity": ".observability.telemetry_models",
    "TelemetryStore": ".observability.telemetry_store",
    "ToolHookDecision": ".agent.base_agent",
    "ToolBatchTurn": ".foundations.contracts",
    "ToolCall": ".foundations.contracts",
    "ToolConcurrency": ".foundations.contracts",
    "ToolResultHandle": ".foundations.contracts",
    "ToolResultJournal": ".memory.context_projection",
    "UserModelSelection": ".agent.orchestrator",
    "UnconfiguredVisionAdapter": ".specifications.vision",
    "VersionedInstructions": ".foundations.contracts",
    "UrlLibJsonTransport": ".agent.openai_compatible",
    "VisionAdapter": ".specifications.vision",
    "VisionProposal": ".specifications.vision",
    "VisionStatus": ".specifications.documents",
    "WorkflowArchitecture": ".state.orchestration_models",
    "WorkerAssignment": ".agent.orchestrator",
    "assemble_initial_context": ".memory.context",
    "core_tool_definitions": ".tools.core",
    "create_mcp_server": ".mcp.server",
    "mcp_tools_as_extensions": ".mcp.client_bridge",
    "registered_tool_name": ".mcp.client_bridge",
    "specification_retrieval_documents": ".specifications.retrieval",
    "metric_observation": ".observability.telemetry_helpers",
    "record_metric_unavailable": ".observability.metrics",
    "record_metric_value": ".observability.metrics",
    "register_standard_metric_definitions": ".observability.metrics",
    "make_provenance_record": ".state.shared_state",
    "WatchdogController": ".tools.supervisor",
    "WatchdogState": ".tools.supervisor",
    "CallableVerificationGate": ".agent.verification",
    "VerificationContext": ".agent.verification",
    "VerificationDecision": ".agent.verification",
    "VerificationGate": ".agent.verification",
    "VerificationGateRegistry": ".agent.verification",
    "ArtifactStatus": ".state.project_state_models",
    "DecisionStatus": ".state.project_state_models",
    "FileProjectStateStore": ".state.project_state_store",
    "InMemoryProjectStateStore": ".state.project_state_store",
    "OpenQuestion": ".state.project_state_models",
    "ProjectArtifactState": ".state.project_state_models",
    "ProjectBlocker": ".state.project_state_models",
    "ProjectDecision": ".state.project_state_models",
    "ProjectState": ".state.project_state_models",
    "ProjectStateEvent": ".state.project_state_models",
    "ProjectStateProjectionPolicy": ".state.project_state_models",
    "ProjectStateProjector": ".state.project_state_engine",
    "ProjectStateReducer": ".state.project_state_engine",
    "ProjectStateView": ".state.project_state_models",
    "ProjectWorkItem": ".state.project_state_models",
    "QuestionOwner": ".state.project_state_models",
    "StageStateField": ".state.project_state_models",
    "StageStateSchema": ".state.project_state_models",
    "StateAction": ".state.project_state_models",
    "StateAuthority": ".state.project_state_models",
    "StateEvidence": ".state.project_state_models",
    "StateTransition": ".state.project_state_models",
    "StateTransitionKind": ".state.project_state_models",
    "WorkItemStatus": ".state.project_state_models",
    "make_project_state": ".state.project_state_models",
    "ClosureWitness": ".specifications.evidence_graph",
    "DiscoveryRouteDecision": ".state.shared_state",
    "DiscoveryRouteStatus": ".state.shared_state",
    "DiscoveryRoutingIndex": ".state.shared_state",
    "DiscoveryRoutingRefs": ".state.shared_state",
    "EvidenceGraph": ".specifications.evidence_graph",
    "EvidenceNode": ".specifications.evidence_graph",
    "EvidenceNodeKind": ".specifications.evidence_graph",
    "EvidenceOmission": ".specifications.evidence_graph",
    "EvidenceRelation": ".specifications.evidence_graph",
    "EvidenceRelationKind": ".specifications.evidence_graph",
    "EvidenceSelectionPolicy": ".specifications.evidence_graph",
    "EvidenceSelectionRequest": ".specifications.evidence_graph",
    "EvidenceSelectionResult": ".specifications.evidence_graph",
    "EvidenceSelectionStatus": ".specifications.evidence_graph",
    "ExactPckpSolver": ".foundations.optimization",
    "GraphAgentBinding": ".agent.graph_agent_executor",
    "GraphAgentBindingContext": ".agent.orchestrator",
    "GraphAgentBindingFactory": ".agent.orchestrator",
    "GraphAgentExecutor": ".agent.graph_agent_executor",
    "GreedyPckpBaseline": ".foundations.optimization",
    "PckpItem": ".foundations.optimization",
    "PckpProblem": ".foundations.optimization",
    "PckpSolution": ".foundations.optimization",
    "PckpStatus": ".foundations.optimization",
    "StructuralContextSelector": ".specifications.evidence_graph",
    "load_pckp_cases": ".foundations.benchmarks",
    "run_pckp_benchmark": ".foundations.benchmarks",
    "write_pckp_benchmark_report": ".foundations.benchmarks",
    "validate_worktree_slug": ".tools.worktrees",
    "ExplorationCandidate": ".integrations",
    "InMemoryJevReceiptStore": ".integrations",
    "InMemoryInteropReceiptStore": ".integrations",
    "InteropFailureMode": ".integrations",
    "InteropOperationStatus": ".integrations",
    "InteropReceipt": ".integrations",
    "InteropReceiptSink": ".integrations",
    "InteropRunEnvelope": ".integrations",
    "JevArchitectureAdvice": ".integrations",
    "JevArchitectureRouter": ".integrations",
    "JevArchitectureRoutingPolicy": ".integrations",
    "JevAdvisoryPolicy": ".integrations",
    "JevAdvisoryVerificationGate": ".integrations",
    "JevChoiceQuestion": ".integrations",
    "JevDecisionRequest": ".integrations",
    "JevExplorationAdvisor": ".integrations",
    "JevNoulQuestion": ".integrations",
    "JevQuestionSpec": ".integrations",
    "JevScoreQuestion": ".integrations",
    "LangChainAgentModelAdapter": ".integrations",
    "LangChainSdkRunnable": ".integrations",
    "LangChainSdkToolFacade": ".integrations",
    "LangGraphApprovalChallenge": ".integrations",
    "LangGraphNodeExecutor": ".integrations",
    "LangGraphSdkNode": ".integrations",
    "LangGraphSdkNodeBinding": ".integrations",
    "TelemetryJevReceiptSink": ".integrations",
    "TelemetryInteropReceiptSink": ".integrations",
    "TypeSafeJevDecisionEvaluator": ".integrations",
    "build_langgraph_state_graph": ".integrations",
    "langgraph_interrupt_payload": ".integrations",
    "parse_structured_sdk_turn": ".integrations",
    "DEFAULT_MAX_ELASTIC_DEPTH": ".state.elastic",
    "DEFAULT_MAX_ELASTIC_NODES": ".state.elastic",
    "ELASTIC_REQUEST_TOOL_NAME": ".state.elastic",
    "ElasticBindingFactory": ".agent.graph_agent_executor",
    "ElasticCapacity": ".state.elastic",
    "ElasticNodeRole": ".state.elastic",
    "ElasticNodeSpec": ".state.elastic",
    "ElasticRefusalCode": ".state.elastic",
    "ElasticReservation": ".state.elastic",
    "ElasticRequestBuffer": ".tools.elastic_requests",
    "ElasticRequestRejected": ".tools.elastic_requests",
    "ElasticRequestToolExecutor": ".tools.elastic_requests",
    "ElasticSpawnRequest": ".state.elastic",
    "GraphCapacityGrant": ".state.elastic",
    "GraphSpawnRecord": ".state.elastic",
    "GraphSpawnStatus": ".state.elastic",
    "MAX_ELASTIC_DEPTH_LIMIT": ".state.elastic",
    "MAX_ELASTIC_NODES_LIMIT": ".state.elastic",
    "MAX_ELASTIC_REQUESTS_PER_RESULT": ".state.elastic",
    "render_elastic_instructions": ".agent.elastic_context",
}

_SUBPACKAGES = frozenset(
    {
        "agent",
        "developer_tools",
        "foundations",
        "integrations",
        "mcp",
        "memory",
        "observability",
        "specifications",
        "state",
        "tools",
    }
)

__all__ = list(_EXPORTS)


def __getattr__(name: str) -> Any:
    module_path = _EXPORTS.get(name)
    if module_path is not None:
        value = getattr(importlib.import_module(module_path, __name__), name)
        globals()[name] = value
        return value
    if name in _SUBPACKAGES:
        return importlib.import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted({*globals(), *_EXPORTS, *_SUBPACKAGES})
