# Copyright (c) 2026 David Michael Indraputra

"""The SDK's standard metric catalogue.

Provider token usage remains explicitly unavailable until a provider adapter
returns a provider-reported usage object; nothing here estimates it.
"""

from __future__ import annotations

from typing import Any

from .telemetry_models import MetricDefinition


def _instrument_for(unit: str, aggregation: str) -> str:
    if unit == "milliseconds":
        return "histogram"
    if aggregation == "sum":
        return "counter"
    return "gauge"


def _definition(
    metric_id: str,
    name: str,
    unit: str,
    direction: str,
    formula: str,
    **kwargs: Any,
) -> MetricDefinition:
    kwargs.setdefault("instrument", _instrument_for(unit, kwargs.get("aggregation", "")))
    return MetricDefinition(
        metric_id=metric_id,
        name=name,
        unit=unit,
        direction=direction,
        formula=formula,
        **kwargs,
    )


STANDARD_METRIC_DEFINITIONS: tuple[MetricDefinition, ...] = (
    _definition(
        "agent.model_turn_attempt_count",
        "Model-turn attempt count",
        "count",
        "lower",
        "count(agent.turn-started)",
        aggregation="sum",
        missing_data_rule="always observed from lifecycle events",
        source_description="BaseAgent lifecycle",
    ),
    _definition(
        "agent.recovery_iteration_count",
        "Recovery iteration count",
        "count",
        "lower",
        "max(model turns - 1, 0)",
        aggregation="sum",
        missing_data_rule="always observed from lifecycle events",
        source_description="BaseAgent lifecycle",
    ),
    _definition(
        "agent.output_rejection_count",
        "Rejected candidate output count",
        "count",
        "lower",
        "count(agent.output-rejected)",
        aggregation="sum",
        missing_data_rule="always observed from lifecycle events",
        source_description="BaseAgent lifecycle",
    ),
    _definition(
        "agent.tool_call_attempt_count",
        "Tool-call attempt count",
        "count",
        "lower",
        "count(agent.tool-requested)",
        aggregation="sum",
        missing_data_rule="always observed from lifecycle events",
        source_description="BaseAgent lifecycle",
    ),
    _definition(
        "agent.tool_failure_count",
        "Failed tool-call count",
        "count",
        "lower",
        "count(agent.tool-completed where status=failed)",
        aggregation="sum",
        missing_data_rule="always observed from lifecycle events",
        source_description="BaseAgent lifecycle",
    ),
    _definition(
        "agent.tool_blocked_count",
        "Blocked tool-call count",
        "count",
        "lower",
        "count(agent.tool-completed where status=blocked)",
        aggregation="sum",
        missing_data_rule="always observed from lifecycle events",
        source_description="BaseAgent lifecycle",
    ),
    _definition(
        "agent.verification_failure_count",
        "Verification failure count",
        "count",
        "lower",
        "count(agent.verification-completed where passed=false)",
        aggregation="sum",
        missing_data_rule="always observed from lifecycle events",
        source_description="BaseAgent lifecycle",
    ),
    _definition(
        "agent.escalation_count",
        "Agent escalation count",
        "count",
        "lower",
        "count(agent.escalated)",
        aggregation="sum",
        missing_data_rule="always observed from lifecycle events",
        source_description="BaseAgent lifecycle",
    ),
    _definition(
        "agent.unsolved_escalation_count",
        "Unsolved agent escalation count",
        "count",
        "lower",
        "1 when terminal status is not completed and an escalation was emitted",
        aggregation="sum",
        missing_data_rule="always observed from terminal record",
        source_description="BaseAgent terminal result",
    ),
    _definition(
        "controller.repair_attempt_count",
        "Controller repair attempts",
        "count",
        "lower",
        "controller record repair_attempts",
        aggregation="max",
        missing_data_rule="observed when a controller failure is recorded",
        source_description="Controller state machine",
    ),
    _definition(
        "controller.escalation_count",
        "Controller escalation count",
        "count",
        "lower",
        "1 when controller phase becomes escalated",
        aggregation="sum",
        missing_data_rule="observed when controller state is persisted",
        source_description="Controller state machine",
    ),
    _definition(
        "context.estimated_input_tokens",
        "Estimated model input tokens",
        "tokens",
        "lower",
        "deterministic SDK estimate",
        aggregation="max",
        missing_data_rule="always observed before model turn; estimate is not provider usage",
        source_description="ContextProjector",
    ),
    _definition(
        "context.working_budget_tokens",
        "Configured working-context budget",
        "tokens",
        "higher",
        "configured context_token_budget",
        aggregation="last",
        missing_data_rule="always observed before model turn",
        source_description="ContextProjectionPolicy",
    ),
    _definition(
        "context.remaining_working_budget_tokens",
        "Remaining estimated working-context budget",
        "tokens",
        "higher",
        "max(context_token_budget - estimated_tokens, 0)",
        aggregation="min",
        missing_data_rule="always observed before model turn",
        source_description="ContextProjector",
    ),
    _definition(
        "retrieval.candidate_count",
        "Grounded retrieval candidate count",
        "count",
        "lower",
        "count(retrieval.completed candidates)",
        aggregation="sum",
        missing_data_rule="observed when a retrieval telemetry sink is configured",
        source_description="GroundedRetrievalService",
    ),
    _definition(
        "retrieval.cache_hit_count",
        "Grounded retrieval cache-hit count",
        "count",
        "higher",
        "1 when retrieval.completed status=cache-hit; otherwise 0",
        aggregation="sum",
        missing_data_rule="observed when a retrieval telemetry sink is configured",
        source_description="GroundedRetrievalService",
    ),
    _definition(
        "context.deadlock_count",
        "Context compaction deadlock count",
        "count",
        "lower",
        "count(CONTEXT_DEADLOCK terminal outcomes)",
        aggregation="sum",
        missing_data_rule="always observed from terminal record",
        source_description="Episode compaction",
    ),
    _definition(
        "context.pask_compaction_count",
        "PASK compaction decisions",
        "count",
        "lower",
        "count(PASK compaction projections)",
        aggregation="sum",
        missing_data_rule="always observed when the PASK strategy is configured",
        source_description="PASK episode compactor",
    ),
    _definition(
        "context.pask_retained_episode_count",
        "PASK retained live episode count",
        "count",
        "higher",
        "count(retained_episode_ids in PASK dossier)",
        aggregation="last",
        missing_data_rule="available when PASK makes a compaction decision",
        source_description="PASK episode compactor",
    ),
    _definition(
        "context.pask_compacted_episode_count",
        "PASK compacted episode count",
        "count",
        "lower",
        "count(compacted_episode_ids in PASK result)",
        aggregation="sum",
        missing_data_rule="available when PASK makes a compaction decision",
        source_description="PASK episode compactor",
    ),
    _definition(
        "context.pask_mandatory_retention_rate",
        "PASK mandatory evidence retention rate",
        "ratio",
        "higher",
        "retained mandatory episode IDs / mandatory episode IDs",
        aggregation="min",
        missing_data_rule="unavailable when no mandatory IDs exist",
        source_description="PASK episode compactor",
    ),
    _definition(
        "context.exact_pckp_compaction_count",
        "Exact PCKP compaction decisions",
        "count",
        "lower",
        "count(EXACT_PCKP compaction projections)",
        aggregation="sum",
        missing_data_rule="available when exact PCKP makes a compaction decision",
        source_description="ExactPckpSolver",
    ),
    _definition(
        "context.exact_pckp_retained_episode_count",
        "Exact PCKP retained live episode count",
        "count",
        "higher",
        "count(retained_episode_ids in exact PCKP dossier)",
        aggregation="last",
        missing_data_rule="available when exact PCKP makes a compaction decision",
        source_description="ExactPckpSolver",
    ),
    _definition(
        "context.exact_pckp_branch_node_count",
        "Exact PCKP branch-and-bound search nodes",
        "count",
        "lower",
        "solver branch_nodes; zero for forest dynamic programming",
        aggregation="sum",
        missing_data_rule="available when exact PCKP makes a compaction decision",
        source_description="ExactPckpSolver",
    ),
    _definition(
        "context.exact_pckp_optimality_gap",
        "Exact PCKP certificate gap",
        "utility",
        "lower",
        "solver-reported exact rational gap converted to a numeric observation",
        aggregation="max",
        missing_data_rule="unavailable only when the solver does not provide a numeric certificate",
        source_description="ExactPckpSolver",
    ),
    _definition(
        "model.provider_context_window_tokens",
        "Provider-reported context window",
        "tokens",
        "higher",
        "provider usage context_window_tokens",
        aggregation="last",
        missing_data_rule=(
            "unavailable until the selected provider adapter reports a context window"
        ),
        source_description="Provider adapter",
    ),
    _definition(
        "model.provider_remaining_context_tokens",
        "Provider-reported estimated remaining context window",
        "tokens",
        "higher",
        "max(context_window_tokens - input_tokens, 0)",
        aggregation="min",
        missing_data_rule=(
            "unavailable unless the provider adapter reports both window and input usage"
        ),
        source_description="Provider adapter",
    ),
    _definition(
        "model.provider_input_tokens",
        "Provider-reported input tokens",
        "tokens",
        "lower",
        "sum(provider usage input_tokens)",
        aggregation="sum",
        missing_data_rule="unavailable until the selected provider adapter reports usage",
        source_description="Provider adapter",
    ),
    _definition(
        "model.provider_output_tokens",
        "Provider-reported output tokens",
        "tokens",
        "lower",
        "sum(provider usage output_tokens)",
        aggregation="sum",
        missing_data_rule="unavailable until the selected provider adapter reports usage",
        source_description="Provider adapter",
    ),
    _definition(
        "model.provider_cached_input_tokens",
        "Provider-reported cached input tokens",
        "tokens",
        "higher",
        "sum(provider usage cached_input_tokens)",
        aggregation="sum",
        missing_data_rule="unavailable unless provider reports cached usage",
        source_description="Provider adapter",
    ),
    _definition(
        "model.provider_reasoning_tokens",
        "Provider-reported reasoning tokens",
        "tokens",
        "lower",
        "sum(provider usage reasoning_tokens)",
        aggregation="sum",
        missing_data_rule=(
            "unavailable unless provider reports a count; no reasoning text is stored"
        ),
        source_description="Provider adapter",
    ),
    _definition(
        "agent.wall_duration_ms",
        "Agent wall duration",
        "milliseconds",
        "lower",
        "agent profile wall_duration_ns / 1e6",
        aggregation="last",
        missing_data_rule="observed when profiler completes",
        source_description="AgentRunProfiler",
    ),
    _definition(
        "agent.process_cpu_duration_ms",
        "Agent process CPU duration",
        "milliseconds",
        "lower",
        "agent profile process_cpu_duration_ns / 1e6",
        aggregation="last",
        missing_data_rule="observed when profiler completes",
        source_description="AgentRunProfiler",
    ),
    _definition(
        "tool.duration_ms",
        "Tool duration",
        "milliseconds",
        "lower",
        "tool profiler duration_ns / 1e6",
        aggregation="sum",
        missing_data_rule="observed for every dispatched tool",
        source_description="AgentRunProfiler",
    ),
    _definition(
        "tool.process_attempt_count",
        "Registered process attempts",
        "count",
        "lower",
        "supervisor process record attempts",
        aggregation="sum",
        missing_data_rule="unavailable for non-process tools",
        source_description="ProcessSupervisor",
    ),
)
